// Fetching Components
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Hero from "@/components/Hero";
import OurStory from "@/components/OurStory";
import Menu from "@/components/Menu";
import Sports from "@/components/Sports";

// Fetching Sanity Data
import { GetStaticProps } from "next";
import { ImageDivider, MenuCategory } from "@/lib/types";
import { getImageDividers } from "@/lib/fetchData";
import { urlFor } from "@/lib/sanityClient";

type HomeProps = {
  imageDividers: ImageDivider[];
};

const Home: React.FC<HomeProps> = ({ imageDividers }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-black w-full">
        <section id="Home">
          <Hero />
        </section>
        <Image
          className="lg:w-screen lg:h-[200px] w-screen "
          alt="section 1"
          src={urlFor(imageDividers[0].image).url()!}
          width={300}
          height={300}
        />
        <section id="OurStory">
          <div className="w-screen h-[96px]" />
          <OurStory />
        </section>
        <Image
          className="lg:w-screen lg:h-[200px] w-screen "
          alt="section 2"
          src={urlFor(imageDividers[1].image).url()!}
          width={300}
          height={300}
        />
        <section id="Menu">
          <div className="w-screen h-[96px]" />
          <Menu />
        </section>
        <Link href={"/"}>
          <div className="flex justify-center items-center text-white bg-black/60 rounded-md font-heading text-3xl lg:text-xl tracker-wide text-center p-3 border mx-4 border-white hover:bg-black/80 mb-16">
            Book a Table
          </div>
        </Link>
        <Image
          className="lg:w-screen lg:h-[200px] w-screen "
          alt="section 2"
          src={urlFor(imageDividers[2].image).url()!}
          width={300}
          height={300}
        />
        <section id="Sports">
          <div className="w-screen h-[96px]" />
          <Sports />
        </section>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const imageDividers = await getImageDividers();
  return {
    props: {
      imageDividers,
    },
  };
};
