// Fetching Components
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Hero from "@/components/Hero";
import OurStory from "@/components/OurStory";
import Menu from "@/components/Menu";
import Sports from "@/components/Sports";

import { Parallax } from "react-parallax";

// Fetching Sanity Data
import { GetStaticProps } from "next";
import { ImageDivider, MenuCategory } from "@/lib/types";
import { getImageDividers } from "@/lib/fetchData";
import { urlFor } from "@/lib/sanityClient";
import Gallery from "@/components/Gallery";
import Events from "@/components/Events";
import Contact from "@/components/Contact";

type HomeProps = {
  imageDividers: ImageDivider[];
};

const Home: React.FC<HomeProps> = ({ imageDividers }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-[#070D0D] w-full">
        <section id="Home">
          <Hero />
        </section>

        <Parallax
          bgImage={urlFor(imageDividers[0].image).url()!}
          strength={150}
          style={{
            backgroundAttachment: "fixed",
            backgroundRepeat: "no-repeat",
            backgroundSize: "auto 100%",
          }}
        >
          <div className="w-screen h-[400px] lg:h-screen " />
        </Parallax>

        <section id="OurStory">
          <div className="w-screen h-[96px]" />
          <OurStory />
        </section>
        <Parallax
          bgImage={urlFor(imageDividers[1].image).url()!}
          strength={200}
          style={{
            backgroundAttachment: "fixed",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% auto",
            width: "100%",
          }}
        >
          <div className="w-screen h-[500px] lg:h-screen relative" />
        </Parallax>

        <section id="Menu">
          <div className="w-screen h-[96px]" />
          <Menu />
        </section>
        <div className="justify-center items-center flex">
          <Link href={"/"} className="justify-center items-center">
            <div className="custom-button mx-4  mb-16 lg:border-4">
              <h1 className="font-heading text-3xl md:text-4xl lg:text-5xl">
                Book a Table
              </h1>
            </div>
          </Link>
        </div>

        <Parallax
          bgImage={urlFor(imageDividers[2].image).url()!}
          strength={250}
          style={{
            backgroundAttachment: "fixed",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% auto",
          }}
        >
          <div className="w-screen h-[500px] lg:h-screen relative" />
        </Parallax>

        <section id="Sports">
          <div className="w-screen h-[96px]" />
          <Sports />
        </section>

        <Parallax
          bgImage={urlFor(imageDividers[3].image).url()!}
          strength={300}
          style={{
            backgroundAttachment: "fixed",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% auto",
          }}
        >
          <div className="w-screen h-[500px] lg:h-screen relative" />
        </Parallax>

        <section id="Gallery">
          <div className="w-screen h-[96px]" />
          <Gallery />
        </section>

        <Parallax
          bgImage={urlFor(imageDividers[4].image).url()!}
          strength={350}
          style={{
            backgroundAttachment: "fixed",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% auto",
          }}
        >
          <div className="w-screen h-[500px] lg:h-screen relative" />
        </Parallax>

        <section id="Events">
          <div className="w-screen h-[96px]" />
          <Events />
        </section>

        <Parallax
          bgImage={urlFor(imageDividers[0].image).url()!}
          strength={150}
          style={{
            backgroundAttachment: "fixed",
            backgroundRepeat: "no-repeat",
            backgroundSize: "100% auto",
          }}
        >
          <div className="w-screen h-[400px] lg:h-screen relative" />
        </Parallax>

        <section id="Contact">
          <div className="w-screen h-[96px]" />
          <Contact />
        </section>
      </main>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const imageDividers = await getImageDividers();
  return {
    props: {
      imageDividers,
    },
  };
};
